language: node_js
node_js:
  - 8.9.4

script:
  - yarn run lint

notifications:
  slack:
    secure: Yg7l2hMYL7c6Xphs2NGwP0EuK/2jm4f/SQSr5+G48a50wKYqKSffgd1jfQe7l3x5JZU1DhhCOSl85aLPgItvuOY390MW6reTkhSBgNuu56qoKVrWCjtxcXvBY5ly6NPCLcDn7fWivNQcJKUV0O7REIlgBgauroD4aZfBjBvjcDfeiKqVeqoidD5CV+DzjN/SwXFJob1NYFgLbx4s6e52CKQwBwWgJKr72CYw0/6+iifbXke828ajsnDdEi1PyNlFGbJQY65oQZ2VmZFC6zVswIrEpDHfNGcSLnnCJ38+AmS8Gs9xTw9fCpW6Yyz+g/o2CgADiKKzkYts3hWE++qvugN7/8iUFx5wleAbXnz10FO5nFP3QtrLVBIeP9Hut5clhApcNREnFV+lM8Z6tC5197UY0HqDiPUrIt3PWX/tYjE8jMvw35jlgLWJh89HH6YwayADFK23EM6lZPWNSd6FW5ZLauPhXg1begJVC8PzmEspiN7KzYIRGJfYHxC89PVVttIeLe5qfpVqesR0wFz3aKbsrDQ13oqIe4sA4bXC7ASdiXx2ZfESF90gZ/MGWVDn5yKKVPNNcXpt2skN+nmrBH5SCdqGbEoeyVqQ1uctWjoIV1aaFt6x9cX+gSYx18e9YPdMLP0Wu86OLUW0K8g+/mYYmvpAh8w1a7fKSQve+IY=
